---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/tags: rpm-build
  name: get-build-target
spec:
  description: Get Koji build target
  params:
    - description: The branch name we build against/from
      name: target-branch
      type: string
    - description: Koji target to use
      name: koji-target
      type: string
    - description: RPM Build environment OCI image to run scripts in
      name: script-environment-image
      type: string
  results:
    - name: koji-build-target
      description: Koji build target
      type: string
    - name: koji-mock-config-template
      type: string
      description: Generated Mock configuration template (as a string)
  steps:
    - name: get-build-target
      image: $(params.script-environment-image)
      env:
        - name: KOJI_TARGET
          value: $(params.koji-target)
      script: |
        #!/bin/bash
        set -ex
        : koji target override: $(params.koji-target)
        target=$( /usr/bin/konflux-select-koji-target "$(params.target-branch)" )
        echo -n "$target" > "$(results.koji-build-target.path)"
        konflux-mock-profile "$(params.target-branch)" "@ARCH@" | tee "$(results.koji-mock-config-template.path)"
