---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/fedora/infrastructure/konflux/rpmbuild-pipeline/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpm-build-pipeline
    appstudio.openshift.io/component: pipeline
    pipelines.appstudio.openshift.io/type: build
  name: ci-for-fedora-pipeline-on-pull-request
  namespace: fedora-on-konflux-tenant
spec:
  params:
    - name: package-name
      value: libecpg
    - name: git-url
      value: "https://src.fedoraproject.org/rpms/libecpg.git"
    - name: revision
      value: "main"
    - name: target-branch
      value: "main"
    - name: self-ref-revision
      value: "{{ revision }}"
    - name: self-ref-url
      value: "{{ source_url }}"
    - name: test-suffix
      value: -rpmbuild-pipeline
    - name: ociStorage
      value: quay.io/konflux-fedora/fedora-on-konflux-tenant/pipeline:on-pr-{{revision}}
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "{{ source_url }}"
      - name: revision
        value: "{{ revision }}"
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
